### ISSUE TITLE
Implement LaravelCaptcha

### ISSUE THREAD

**Issue by nfebe** [ABWebDevelopers/oc-forms-plugin#13]
Google captcha is quite annoying for some users and a lot of people don't know how to use it, sometimes people have to fill it multiple times. It works though.

However, we could include the laravel captcha itself for those  who want it! NO API Keys would be required and these captcha provided a better user experience.

REF : https://github.com/mewebstudio/captcha

Requirements:

- Introduce composer.json
- Require laravelcaptcha
- Include as option for validators
- Add option to component.

I would be able to quickly do this, if its sounds good and someone provides me a little help with the context on how exactly the validation code is structure, I have read through however, wont be nice taking so much time on it if someone can speed up the process by throwing more context information.

**Comment by bennothommo** [comment]
@Fenn-CS Thanks for your suggestion, however, that appears to be an easily-broken CAPTCHA system. Similar CAPTCHAs have already been defeated by automated tools. We may investigate ways of allowing people to roll out their own CAPTCHA system with this plugin, but probably won't bring this system in directly at this stage.
