### ISSUE TITLE
Submit Button does not submit anything

### ISSUE THREAD

**Issue by chrisvidal** [ABWebDevelopers/oc-forms-plugin#23]
When I click the Submit button, nothing is happening, no js error, no trace server side from the components.

**Comment by bradietilley** [comment]
This by default utilises the OctoberCMS JS/AJAX Framework, Have you imported the framework + extras in your footer? `{% framework extras %}`

**Comment by chrisvidal** [comment]
O ok it must be that, this line is commented in my code. thanks @bradietilley
