### ISSUE TITLE
Can't get this addon to work

### ISSUE THREAD

**Issue by tjaynl** [ABWebDevelopers/oc-forms-plugin#28]
So i tried this plugin on a couple of website and i can't seem to get it to work.
instead of sending the form information it copies this right behind the domain like in the following example:

https://domainname.com/?name=test&email=test%40test.nl&comment=test

I have { framework.extras } in my script tag as such:
<script src="{{ [ '@jquery', '@framework', '@framework.extras', 'assets/js/app.js' ]|theme }}"></script>

**Comment by bradietilley** [comment]
This is what I normally have and it's always worked

```html
<head>
    <!-- jQuery -->
    <!-- other important scripts and polyfills that don't rely on October Framework that also won't negatively affect load of website -->
</head>
<body>
...
    <footer>
        {% framework extras %} <!-- Framework + Extras -->

        {% scripts %}

        <!-- other scripts that rely on framework APIs or JS files that choke the page load -->
    </footer>
</body>
```

I would recommend you try split some of those JS files, especially jQuery and Framework files. If you individually specify these JS files, the browser can leverage its own caching, whereas combining forces the browser to download everything every time any small JS file is updated. 

Try my suggestion above and if that doesn't work I may be able to take another look.

**Comment by tjaynl** [comment]
First of thank you for the reply,

I tried using your method but it had no success, even if i split all/most of the js files to load on there own it gives me te same error or it doesn't do anything at all.

**_Update_**:
I got the following error when puzzeling with the script tags:

"Expected response code 250 but got code "550", with message "550 5.7.1 Relaying denied "" on line 457 of /home/inenophethuis/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php

**Comment by bradietilley** [comment]
Sounds like the plugin is now `POST`ing correctly as Swift would only be used once the form submits and sends off emails. It seems that you have some mail configuration issues going on there. I've never seen code 550 from Swift, so unfortunately I won't be able to provide much there.

**Comment by tjaynl** [comment]
Oops my bad, i forgot the configure the mail settings indeed, sorry about that.

It all seems to work with the follwing:

`
  <script src="{{ [
    'assets/js/script',
    'assets/js/vendor'
  ]|theme }}"></script>

{% scripts %}
        
<script src="{{ [
    '@jquery',
    '@framework',
    '@framework.extras'
]|theme }}"></script>`


Thanks for the help!
