### ISSUE TITLE
No query results for model

### ISSUE THREAD

**Issue by bandibandi** [ABWebDevelopers/oc-forms-plugin#3]
After installation i got this message, when i try to open a cms page, inside this plugin with the default contact form:

We're sorry, but an unhandled error occurred. Please see the details below.

No query results for model [ABWebDevelopers\Forms\Models\Form].
C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php line 414

**Comment by bradietilley** [comment]
Can you please confirm that the `formCode` property for the component is set to a valid `code` (I believe the Contact Form one is `contact_form`).

If it is set to that I'll have a look to see if I can replicate the issue. If you paste in the cms page / layout's file contents including the header section (i.e. before `==` as well)

**Comment by bandibandi** [comment]
Right, it was a typo.
Works well, thank you.
