### ISSUE TITLE
my submissions are not shown in Submissions are in the plugin page

### ISSUE THREAD

**Issue by RustemHesenov** [ABWebDevelopers/oc-forms-plugin#31]
Hello, dear, plug-in author!

I used your plug-in on my October cms website.

But ı have some problems.

I have created a new custom form and an added to test page via component. But when I fill and submit the form my submissions are not shown in Submissions are in the plugin page.

field results added to URL like this one: `http://localhost:8888/testwebsite/testpage?name=Rustem&surname=Hesenov`

How can I solve this problem?

I need your support imminently

**Comment by bennothommo** [comment]
@RustemHesenov have you enabled "Saves data?" in the settings page?

**Comment by bradietilley** [comment]
@RustemHesenov This is a sign that the JS is not running correctly so it's likely that you have not imported the Framework Extras JS library.

To do this you must add `{% framework extras %}` into your footer partial (or whatever layout uses this form). If you already have a `{% framework %}` definition in your partial/layout, simply add the work `extras` after `framework`.

**Comment by RustemHesenov** [comment]
> @RustemHesenov This is a sign that the JS is not running correctly so it's likely that you have not imported the Framework Extras JS library.
> 
> To do this you must add `{% framework extras %}` into your footer partial (or whatever layout uses this form). If you already have a `{% framework %}` definition in your partial/layout, simply add the work `extras` after `framework`.

Really thank you! I solved the problem!
