### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by fiskeren** [ABWebDevelopers/oc-forms-plugin#32]
Hi,

Just implemented the Custom Forms plugin for October CMS, but it doesn't seem to work. I can see in the console, that the JavaScript gives:
```
VM130 custom-form.js:3 Uncaught ReferenceError: $ is not defined
    at VM130 custom-form.js:3
(anonymous) @ VM130 custom-form.js:3
setInterval (async)
(anonymous) @ VM130 custom-form.js:2
```

![image](https://user-images.githubusercontent.com/7452027/109433237-42435200-7a07-11eb-8c19-55581794d29b.png)

I googled my way in to understand that I need jQuery in my page somewhere, but haven't found the right one yet - Can you please help which jQuery library I need to add to get it work? 

After adding jQuery to my site:
![image](https://user-images.githubusercontent.com/7452027/109433752-f2b25580-7a09-11eb-85b1-1a79f6785dc0.png)

**Comment by bennothommo** [comment]
@fiskeren the October CMS AJAX framework is required for this plugin to work. You need to have `{% framework extras %} ` in your layout before any other scripts are loaded.
