### ISSUE TITLE
Unable to determine the default value for the setect input type

### ISSUE THREAD

**Issue by itislanet** [ABWebDevelopers/oc-forms-plugin#38]
Hello, today I tried to configure a form but it was impossible to define the default value in the select inputs.

I have made some changes in the consecutive lines to the 506 of the file in this path "/abwebdevelopers/forms/classes/HtmlGenerator.php"

I attach it in case someone may need it or want to make the change to improve this functionality.

if (!empty($field->placeholder) && empty($field->default)){
        $el->addChild(new HtmlOption([
            'value' => '',
            'selected' => true,
            'disabled' => $field->required,
            'node' => $field->placeholder,
        ]));
		}

        foreach ($field->getOptions() as $option) {
            if ($option->is_optgroup) {
                $optgroup = new HtmlOptgroup([
                    'label' => $option->option_label,
                ]);

                foreach ($option->options as $option) {
                    $optgroup->addChild(new HtmlOption([
						
					    'value' => $option->option_code,
                        'node' => $option->option_label,
                    ]));
                }

                $el->addChild($optgroup);

                continue; 
            }
			if ($option->option_code == $field->default && !empty($option->option_code)) {
				$el->addChild(new HtmlOption([
				'selected' => true,
                'value' => $option->option_code,
                'node' => $option->option_label,
            ]));
				}
			else {
				$el->addChild(new HtmlOption([
				
                'value' => $option->option_code,
                'node' => $option->option_label,
            ]));
			}	
            
        }

**Comment by bradietilley** [comment]
Thanks for your contribution, I have added this to v1.5.1

Feel free to add any other features that you can think of via PRs :smile:
