### ISSUE TITLE
Template override

### ISSUE THREAD

**Issue by erwanregnier** [ABWebDevelopers/oc-forms-plugin#7]
Since the last update 1.1.0 the form.htm override in the partial component alias folder is ignored.
The default.htm is overrided but the form.htm

**Comment by bradietilley** [comment]
This is a breaking change (1.1.x) - I wasn't too sure how to launch a breaking change with October as the docs are kinda thin.

If you would like to, you may add in backwards compatibility in a PR and I'll merge it in, however personally I am against using Twig to generate complicated conditional elements hence the change.

**Comment by erwanregnier** [comment]
I understand the change to avoid Twig, the problem is that now it's not possible anymore to custom the code inside the form (not the fields code but the form template structure itself), that's a pity.
I just wanted to know if it was ignoring the template file because the form.htm still exists in the plugin folder, but it's not used anymore so it was a bit confusing.

I don't need a backward compatibility, I'll just try to make my form working again in another way,
thanks :)

**Comment by bradietilley** [comment]
Just to clarify - you can listen in on the `abweb.forms.afterRenderPartial` event which will give you a referenced `$form` which you can update.
