### ISSUE TITLE
Select field array error

### ISSUE THREAD

**Issue by 3309** [ABWebDevelopers/oc-forms-plugin#9]
htmlspecialchars() expects parameter 1 to be string, array given.

at : abwebdevelopers/forms/controllers/submission/_details.htm line 39   

     <li>
            <b>Form Data:</b>
            <ul>
                <?php foreach ($submission->data as $field => $value): ?>
                <li>
                    <b class="inline-data"><?= ucwords(str_replace('_', ' ', $field)) ?>:</b>
                    <pre class="inline-data"><?= htmlspecialchars($value) ?></pre>
                </li>
                <?php endforeach; ?>
            </ul>
        </li>
    </ul>
</div>

array and string problems?
any way to change

**Comment by bradietilley** [comment]
Thanks for pointing this out, I have released a bugfix version: 1.1.3

Please note, if you are on 1.0.x, the renderer changes to a more rigid approach in 1.1 so if you have overridden partials for fields/the form, beware
